GET http://localhost:4004/catalog/Books

###
GET http://localhost:4004/catalog/Authors

###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{
    "ID":10,
    "title":"Kirti"
}

